config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [ :index, :show, :edit, :update ] do
    resources :bookings, only: [:create ]
  end

  resources :bookings, only: [ :new, :index, :destroy, :create, :show ] do
  resources :reviews, only: [ :new, :create ]
  end

  get 'my_bookings', to: 'pages#my_bookings'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'show', to: 'bookings#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :location, :pet_sitter])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :location, :pet_sitter])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:name, :address, :description, :price, :picture)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def my_bookings
  end

  def contact
  end

  def show
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:query].present?
      @users = User.where("location ILIKE ?", "%#{params[:query]}%")
    else
      @users = User.all
      @markers = @users.geocoded.map do |user|
        {
          lat: user.latitude,
          lng: user.longitude,
          info_window: render_to_string(partial: "info_window", locals: { user: user }),
          image_url: helpers.asset_url('petsittericon.jpg')
        }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Booking form</h2>

    <%= simple_form_for @booking do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%#= f.input :pet, required: false, :collection => [['Dog',1],['Cat',2], ['Dragon',2]] %>

      <%= f.button :submit, "Go", class: "btn btn-primary", id: "btn1" %>


    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= image_path 'Banner4.jpg' %>')">
  <div class="black-text">
    <h3 class="black-text">Booking confirmed</h3>
    <h3>You're all set, time to relax!</h3>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetSitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <link rel="stylesheet" type= "text/css" href="css/style.css"> %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,500&amp;subset=latin-ext" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@300&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="main-content">
      <%= render "shared/navbar" %>
      <div class="yielded-content">
        <%= yield %>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= image_path 'Banner2.jpg' %>')">
  <div>
    <h1>Our Story</h1>
    <h2>We understand pets</h2>
    <p>We have been connecting hundreds of thousands of pet parents <br>
    with loving pet sitters and we can’t wait to do the same for you.</p>
  </div>
</div>

<div class="card-product">
  <div class="card-product-infos">
  <%= image_tag 'Banner3.jpg' %>
    <h3>Our Purpose</h3>
    <p>We want to make it easy for you to find and book a pet sitter in your
      local neighbourhood. So whether you are going away, need someone to drop in to
      check on your pet while you’re at work or take your dog for a sniff around
      the block, we’ve got a sitter for you</p>
  </div>

  <div class="card-product-infos">
    <h3>Our Values</h3>
    <p>At Pet Sitter, we aim to foster a thriving community dedicated to connecting
    and improving the wellbeing of pets. We understand that it takes a lot of faith
    to trust someone to look after a fur member of your family. This is why trust
    and safety is a very big part of Pet Sitter’s core values.</p>
    <%= image_tag 'Banner1.jpg' %>
  </div>

  <div class="card-product-infos">
  <%= image_tag 'Banner2.jpg' %>
    <h3>Why us ?</h3>
    <ul>
      <p><strong>When you book through Pawshake you can expect:</strong></p>
      <br>
      <li>Secure online payment</li>
      <li>Verified reviews</li>
      <li>Happiness Guarantee</li>
      <li>Booking Guarantee</li>
    </ul>
  </div>
</div>

<div class="card-review" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= image_path 'Banner3.jpg' %>')">
  <div>
  <h3>Guest Review</h3>
  <p>"James is an amazing pet sitter. He took care of our French Bulldog as <br>
  if it was his own. We enjoyed receiving tons of pictures every day. <br>
  We could see he is truly an animal lover and that our frenchie was <br>
  very happy - spoiled rotten. James is so much more than just a pet sitter!"</p>
  <p>⭐️⭐️⭐️⭐️⭐️</p>
  <p id="signature">by Ahlee</p>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <h1>Contact Us</h1>
  <form action="action_page.php">

    <label for="fname">First Name</label>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">

    <label for="lname">Last Name</label>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">

    <label for="subject">Subject</label>
    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

    <input type="submit" value="Submit">

  </form>
</div>

app/views/pages/home.html.erb
<%= form_tag users_path, method: :get do %>
  <div class="search-bar search-form-control form-group">
    <%= text_field_tag :query,
      params[:query],
      class: "search-bar form-control string required",
      placeholder: "Where is your location ?"
    %>
    <%= button_tag "Search", type: "submit", class: "btn" do %>
      <i class="fas fa-search"></i> Search
    <% end %>
  </div>
<% end %>


<div class="banner">
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="main-text">
        <h1>Find a loving local pet sitter or dog sitter</h1>
        <p>Who treats your pet like family</p>
        <%= link_to "Discover our pet sitters!", users_path, class: "btn2"  %>
      </div>
      <div class="carousel-item active carousel-div">
        <%= image_tag 'Banner1.jpg' %>
      </div>
      <div class="carousel-item carousel-div">
        <%= image_tag 'Banner2.jpg' %>
      </div>
      <div class="carousel-item carousel-div">
        <%= image_tag 'Banner3.jpg' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/login_form.html.erb
<h2>Log in</h2>

<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-inputs">
    <%= f.input :email,
                required: false,
                autofocus: true,
                input_html: { autocomplete: "email" } %>
    <%= f.input :password,
                required: false,
                input_html: { autocomplete: "current-password" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Welcome Back" %>
  </div>
<% end %>

app/views/pages/signup_form.html.erb
<h2>Sign up</h2>
<p>Hello, who is this ?</p>

<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "email" }%>
    <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :password_confirmation,
                required: true,
                input_html: { autocomplete: "new-password" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Join Us" %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Copyright © 2013-2021 Pet Sitter Inc. All Rights Reserved.
    <a href="#">Terms and Conditions</a> and <a href="#">Privacy &amp; Cookie Policy</a>.
    <br>
    Find a loving local pet sitter with <i class="fas fa-heart"></i> at Pet Sitter.
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="header">
  <div class="logo">
  <%= link_to root_path do %>
    <h1>MY <span>PET SITTER</span> <i class="fas fa-paw"> </i></h1>
    <% end %>
  </div>

  <div>
    <ul class="navigation">

      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Pet Sitters", users_path %></li>
      <li><%= link_to "Contact", contact_path %></li>

    </ul>
  </div>
  <div>
    <img class="avatar" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
  </div>
</div>

app/views/users/_info_window.html.erb
<h2><%= user.name %></h2>
<p><%= user.location %></p>

app/views/users/index.html.erb
<div class="team-boxed">
  <div class="container">
    <div class="intro">
      <h2 class="text-center">Wonderful and caring pet sitters all around the world</h2>
      <p class="text-center">Because your pets matter, wherever you live</p>
    </div>
    <div class="people" id="cards" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      <%= link_to new_booking_path, class: 'card-user-link' do %>
        <div class="col-12 item">
          <% @users.each_with_index do |user, index| %>
            <% if user.pet_sitter %>
              <div class="box">
                <div class= "profil">
                  <img class="rounded-circle" src="https://source.unsplash.com/random/200x200">
                    <h2><%= user.name %></h2>
                    <p><%= user.location %></p>
                </div>
                <div class="user-map" id="map-<%= index %>"
                    style="width: 100%; height: 250px"
                    data-position="[<%= user.longitude %>, <%= user.latitude %>]"
                    data-popup="<%= render partial: 'info_window', locals: { user: user } %>"
                    data-image="<%= asset_url('petsittericon.jpg') %>"
                  >
                </div>
              </div>
            <% end %>
          <% end %>

              <%#<div class="social"><a href="#"><i class="fa fa-facebook-official"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div> %>
            <%# </div> %>
        </div>
      <% end %>
    </div>
  </div>
</div>

            <%#<div class="social"><a href="#"><i class="fa fa-facebook-official"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div> %>
          <%# </div> %>